info = input(str('Digite algo:'))
print(type(info))
print(info.isnumeric())
print(info.isalpha())
print(info.isalnum())
print(info.isupper())
print(info.islower())
print(info.isprintable())
print(int(info))
print(bool(info))
print(float(info))
print(info.isdecimal())
